# Settings
line-length = 120  # Keep aligned with .editorconfig

[format]
line-ending = "lf" # Use `\n` line endings

[lint]
select = ["ALL"]

ignore = [
    "ANN",    # flake8-annotations - MyPy is checking annotations
    "S311",   # flake8-bandit - cryptographically weak `random` used
    "RET504", # flake8-return - unnecessary assignment before `return` statement
    "COM812", # flake8-commas - mIssing trailing comma
    "D200",   # pydocstyle - unnecessary multiline docstring
    "D203",   # pydocstyle - blank line before class docstring
    "D212",   # pydocstyle - docstring not on 1st line after opening quotes
    "D400",   # pydocstyle - missing trailing period in docstring
    "D401",   # pydocstyle - docstring first lines are not in an imperative mood
    "D415",   # pydocstyle - missing terminal punctuation (.,? or !)


    # "PERF401" # Perflint - `for` loop can be replaced by list comprehension

    # Consider removing these for projects/publication
    "D1",     # pydocstyle - missing docstring
    "ERA001", # eradicate - found commented out code
    "T201",   # flake8-print - `print` found
    "T203",   # flake8-print - `pprint` found
]

[lint.per-file-ignores]
"tests/*.py" = ["S101"]  # Use of `assert` detected
"test_*.py"  = ["S101"]
